### ISSUE TITLE
ImportError: cannot import name 'json' from 'itsdangerous'

### ISSUE THREAD

**Issue by michaeltoohig** [serebrov/flask-vue-starter#54]
itsdangerous is not pinned to a particular version so while Flask remains at 1.1.1, the install itsdangerous version no longer allows importing 'json' package and instead suggests importing json from the standard library.

itsdangerous will need to be pinned to version 2.0.1 or update Flask to version 2.x which may require updates to more packages than you want to deal with at the moment.

https://itsdangerous.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

**Comment by michaeltoohig** [comment]
I found `Jinja2` package also needs to be pinned.

**Comment by serebrov** [comment]
I also see this error trying to start the docker setup:

> ImportError: cannot import name 'escape' from 'jinja2' (/backend/venv/lib/python3.7/site-packages/jinja2/__init__.py)

I will pin dependencies for now and will try to upgrade them later.

**Comment by serebrov** [comment]
Fixed in #55.
